### ISSUE TITLE
Release the library as ES6 module

### ISSUE THREAD

**Issue by karoletrych** [TheCloudConnectors/cron-validator#4]
Release the library as ES6 module, so it can be used with `import`.

**Comment by GuillaumeRochat** [comment]
We've been doing the `import` syntax in typescript without issue on our side, so maybe it's just something we misconfigured in the tsconfig.json, which impacts the generated index.d.ts?

Was the `require` statements instead of an `import` added from an auto-import?

Could it be because we configured the target to a quite old version of js?

**Comment by karoletrych** [comment]
Nevermind, it works with
`import {isValidCron} from 'cron-validator'`

**Comment by GuillaumeRochat** [comment]
@karoletrych Ah, good! I will adjust the README so it reflects that.
